/* Auto-generated by genmsg_cpp for file /home/georg/Software/ROS/ethzasl_sensor_fusion/ssf_core/msg/ext_state.msg */
#ifndef SSF_CORE_MESSAGE_EXT_STATE_H
#define SSF_CORE_MESSAGE_EXT_STATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Pose.h"
#include "geometry_msgs/Vector3.h"

namespace ssf_core
{
template <class ContainerAllocator>
struct ext_state_ {
  typedef ext_state_<ContainerAllocator> Type;

  ext_state_()
  : header()
  , pose()
  , velocity()
  {
  }

  ext_state_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pose(_alloc)
  , velocity(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::Pose_<ContainerAllocator>  pose;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  velocity;


  typedef boost::shared_ptr< ::ssf_core::ext_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssf_core::ext_state_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ext_state
typedef  ::ssf_core::ext_state_<std::allocator<void> > ext_state;

typedef boost::shared_ptr< ::ssf_core::ext_state> ext_statePtr;
typedef boost::shared_ptr< ::ssf_core::ext_state const> ext_stateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ssf_core::ext_state_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ssf_core::ext_state_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ssf_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ssf_core::ext_state_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ssf_core::ext_state_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ssf_core::ext_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e034f695cee32efa98d5cb7e960000e2";
  }

  static const char* value(const  ::ssf_core::ext_state_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe034f695cee32efaULL;
  static const uint64_t static_value2 = 0x98d5cb7e960000e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssf_core::ext_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ssf_core/ext_state";
  }

  static const char* value(const  ::ssf_core::ext_state_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ssf_core::ext_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Pose          pose\n\
geometry_msgs/Vector3       velocity\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::ssf_core::ext_state_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ssf_core::ext_state_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ssf_core::ext_state_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ssf_core::ext_state_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pose);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ext_state_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssf_core::ext_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ssf_core::ext_state_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "velocity: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SSF_CORE_MESSAGE_EXT_STATE_H

